version: 4.0.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2022
    
branches:
    only:
    - main
    
environment:
    nodejs_version: 14.3.0
    npm_auth_token:
        secure: utvTJFeOvz8YUfgc/z87ERaWZs4tDNSAe/atkmUagrQjaxniSCqXn0Q4U1UVx1ST
    
install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- ps: Install-Product node $env:nodejs_version
- ps: >- 
    npm install --loglevel=error
    
    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

build_script:
- mkdir -p dist
- copy README.md dist\
- copy package.json dist\
- copy src\jquery.listadecompras.css dist\
- copy src\jquery.listadecompras.js dist\
- cd dist
- git config user.email "build@appveyor.com"
- git config user.name "AppVeyor"
- npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
- npm publish
- cd ..
- cmd: nuget pack jquery.listadecompras.nuspec -Version %APPVEYOR_BUILD_VERSION%

after_build:
- 7z a -tzip -mx9 "jquery.listadecompras.%APPVEYOR_BUILD_VERSION%.zip" dist

artifacts:
- path: '**\*nupkg'
  name: Package
  
- path: jquery.listadecompras.%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile

deploy:
- provider: NuGet
  api_key: $(NUGET_TOKEN)
  skip_symbols: true
  on:
   branch: main
  artifact: Package

- provider: GitHub
  on:
   branch: main
  tag: $(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
  artifact: ZipFile, Package
